#pragma once

#define TITANIUM_MEMORY_READ_REQUEST_32BIT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4554, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define TITANIUM_MEMORY_WRITE_REQUEST_32BIT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4584, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

#define TITANIUM_MEMORY_READ_REQUEST_64BIT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x7554, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define TITANIUM_MEMORY_WRITE_REQUEST_64BIT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x7584, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

typedef struct _TITANIUM_KERNEL_MEMORY_READ_WRITE_REQUEST_32BIT
{
	ULONG ProcessID;
	ULONG pSource;
	ULONG pTarget;
	ULONG Size;
} TITANIUM_KERNEL_MEMORY_READ_WRITE_REQUEST_32BIT, *PTITANIUM_KERNEL_MEMORY_READ_WRITE_REQUEST_32BIT;

typedef struct _TITANIUM_KERNEL_MEMORY_READ_WRITE_REQUEST_64BIT
{
	ULONG64 ProcessID;
	ULONG64 pSource;
	ULONG64 pTarget;
	ULONG64 Size;
} TITANIUM_KERNEL_MEMORY_READ_WRITE_REQUEST_64BIT, *PTITANIUM_KERNEL_MEMORY_READ_WRITE_REQUEST_64BIT;

#define TITANIUM_SET_TARGET_IMAGE_REQUEST_32BIT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4694, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define TITANIUM_SET_TARGET_IMAGE_REQUEST_64BIT			CTL_CODE(FILE_DEVICE_UNKNOWN, 0x7694, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

typedef struct _TITANIUM_KERNEL_SET_TARGET_IMAGE_REQUEST_32BIT
{
	UINT32	ImageIndex;
	ULONG	pTargetImageBuffer;
	UINT32	TargetImageBufferSize;
} TITANIUM_KERNEL_SET_TARGET_IMAGE_REQUEST_32BIT, *PTITANIUM_KERNEL_SET_TARGET_IMAGE_REQUEST_32BIT;

typedef struct _TITANIUM_KERNEL_SET_TARGET_IMAGE_REQUEST_64BIT
{
	UINT32	ImageIndex;
	ULONG64	pTargetImageBuffer;
	UINT32	TargetImageBufferSize;
} TITANIUM_KERNEL_SET_TARGET_IMAGE_REQUEST_64BIT, *PTITANIUM_KERNEL_SET_TARGET_IMAGE_REQUEST_64BIT;

#define TITANIUM_GET_TARGET_IMAGE_INFO_REQUEST_32BIT		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x4310, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)
#define TITANIUM_GET_TARGET_IMAGE_INFO_REQUEST_64BIT		CTL_CODE(FILE_DEVICE_UNKNOWN, 0x7310, METHOD_OUT_DIRECT, FILE_ANY_ACCESS)

typedef struct _TITANIUM_KERNEL_GET_TARGET_IMAGE_INFO_REQUEST_32BIT
{
	UINT32	ImageIndex;
	ULONG	pTargetImageInfo;
} TITANIUM_KERNEL_GET_TARGET_IMAGE_INFO_REQUEST_32BIT, *PTITANIUM_KERNEL_GET_TARGET_IMAGE_INFO_REQUEST_32BIT;

typedef struct _TITANIUM_KERNEL_GET_TARGET_IMAGE_INFO_REQUEST_64BIT
{
	UINT32	ImageIndex;
	ULONG64	pTargetImageInfo;
} TITANIUM_KERNEL_GET_TARGET_IMAGE_INFO_REQUEST_64BIT, *PTITANIUM_KERNEL_GET_TARGET_IMAGE_INFO_REQUEST_64BIT;
